version: 2
jobs:
  test:
    docker:
      - image: hiroga/terraform-gcp
    steps:
      - checkout
      - run:
          name: activate service account for access Cloud Storage
          command: |
            echo ${GCLOUD_SERVICE_KEY} | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${TF_VAR_project_id}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_REGION}
            gcloud config list
      - run:
          name: create credential file for Terraform
          command: |
            echo ${GCLOUD_SERVICE_KEY} > ./key.json
      - run:
          name: test
          command: |
            export GOOGLE_APPLICATION_CREDENTIALS="./key.json"
            terraform init
            terraform plan

  build:
    docker:
      - image: hiroga/terraform-gcp
    steps:
      - checkout
      - run:
          name: activate service account for access Cloud Storage
          command: |
            echo ${GCLOUD_SERVICE_KEY} | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${TF_VAR_project_id}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_REGION}
            gcloud config list
      - run:
          name: create credential file for Terraform
          command: |
            echo ${GCLOUD_SERVICE_KEY} > ./key.json
      - run:
          name: deploy
          command: |
            export GOOGLE_APPLICATION_CREDENTIALS="./key.json"
            terraform init
            terraform apply
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build