version: 2
jobs:
  build:
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - run: terraform --help
  test:
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - run: ls
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test