version: 2
jobs:
  test:
    docker:
      - image: hiroga/terraform-gcp-ts
    steps:
      - checkout
      - run:
          name: npm
          command: |
            npm install
            mv ./node_modules ./src/node_modules
            npm test
      - run:
          name: create credential file for Terraform
          command: |
            echo ${GCLOUD_SERVICE_KEY} > ./key.json
      - run:
          name: test
          command: |
            export GOOGLE_APPLICATION_CREDENTIALS="./key.json"
            terraform init
            terraform plan

  build:
    docker:
      - image: hiroga/terraform-gcp-ts
    steps:
      - checkout
      - run:
          name: npm
          command: |
            npm install --production
            mv ./node_modules ./src/node_modules
      - run:
          name: create credential file for Terraform
          command: |
            echo ${GCLOUD_SERVICE_KEY} > ./key.json
      - run:
          name: deploy
          command: |
            export GOOGLE_APPLICATION_CREDENTIALS="./key.json"
            terraform init
            terraform apply -auto-approve -lock=false
workflows:
  version: 2
  build_and_test:
    jobs:
      - test:
          context: cc-hiroga-gcp-rss-webhook
      - build:
          context: cc-hiroga-gcp-rss-webhook