version: 2
jobs:
  build:
    docker:
      - image: hiroga/terraform-gcp
    steps:
      - checkout
      - run:
          name: deploy
          command: |
            terraform init
            terraform plan
  test:
    docker:
      - image: hiroga/terraform-gcp
    steps:
      - checkout
      - run: terraform fmt
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test